import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 45, paddingBottom: 15 },
  topIcon: { width: 18, height: 18, tintColor: '#FFF' },
  brandGroup: { alignItems: 'center' },
  brandLogo: { width: 22, height: 22 },
  brandText: { color: '#FD02A8', fontSize: 10, fontWeight: 'bold' },
  topRightIcons: { flexDirection: 'row', gap: 15 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 80 },
  searchBar: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#FD02A8', borderRadius: 8, paddingHorizontal: 12, height: 40, marginVertical: 15, backgroundColor: 'rgba(0,0,0,0.6)' },
  searchIcon: { width: 14, height: 14, tintColor: '#666', marginRight: 10 },
  searchInput: { flex: 1, color: '#FFF', fontSize: 11 },
  banner: { borderWidth: 1, borderColor: '#FD02A8', borderRadius: 10, padding: 15, marginBottom: 20, backgroundColor: 'rgba(253, 2, 168, 0.1)' },
  bannerTag: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },
  bannerTitle: { color: '#FFF', fontSize: 22, fontWeight: 'bold', marginVertical: 5 },
  bannerBtn: { backgroundColor: '#FD02A8', paddingVertical: 8, paddingHorizontal: 15, borderRadius: 6, alignSelf: 'flex-start' },
  bannerBtnText: { color: '#FFF', fontSize: 11, fontWeight: 'bold' },
  sectionTitle: { color: '#FFF', fontSize: 14, fontWeight: 'bold', marginBottom: 12 },
  horizontalScroll: { marginBottom: 20 },
  gameCard: { width: 110, marginRight: 12, backgroundColor: '#111', borderRadius: 8, padding: 8, borderWidth: 1, borderColor: '#222' },
  gameImagePlaceholder: { width: '100%', height: 90, backgroundColor: '#222', borderRadius: 6, marginBottom: 8 },
  gameTitle: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },
  gamePrice: { color: '#FD02A8', fontSize: 10, marginTop: 4 },
  categoriesGrid: { flexDirection: 'row', justifyContent: 'space-between' },
  categoryCard: { width: '22%', aspectRatio: 1, borderWidth: 1, borderColor: '#FD02A8', borderRadius: 8, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.6)' },
  categoryIcon: { width: 24, height: 24, resizeMode: 'contain', marginBottom: 6 },
  categoryText: { color: '#FFF', fontSize: 8, fontWeight: 'bold' },
  bottomNav: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', height: 60, backgroundColor: '#050505', borderTopWidth: 1, borderTopColor: '#222', position: 'absolute', bottom: 0, left: 0, right: 0 },
  navItem: { alignItems: 'center' },
  navIcon: { width: 18, height: 18, tintColor: '#666' },
  navText: { color: '#666', fontSize: 8, marginTop: 4 },
});